stages:
  - build
  - nothing
  - test

jobs:
  build:
    stage: build
    image: node:12-alpine
    workspace: shared
    services:
      - redis:alpine
    before_script:
      - echo before_script
    script:
      - ls -la /
      - ls -la /build
      - ps -a
      - ulimit -a
      - sleep 10
      - echo fuck
      - echo "shared workspace"
    after_script:
      - echo yayfuck
  build2:
    stage: build
    image: node:12-alpine
    services:
      - redis:alpine
    script:
      - ls -la /
      - echo "none workspace"

  test:
    stage: test
    image: alpine
    workspace: shared
    script:
      - echo fuck
      - sleep 10
      - echo 'except develop'
      - echo 'quang phu' > sharedWorkspace
    except:
      branches:
        - develop
  test2:
    stage: test
    image: alpine
    script:
      - sleep 10
      - echo fuck
      - echo "None workspace"
    except:
      branches:
        - master
  test3:
    stage: test
    image: alpine
    workspace: shared
    script:
      - sleep 10
      - echo fuck
      - echo "read file shared workspace"
      - cat sharedWorkspace
      - composer install
      - composer sniff
    except:
      branches:
        - develop
